# Generated by Django 4.0.1 on 2023-04-10 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artworks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorsOfText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Composers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Performances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_artworks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardfile.artworks')),
            ],
        ),
        migrations.CreateModel(
            name='Performers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('id_performers', models.ManyToManyField(to='cardfile.Performances')),
            ],
        ),
        migrations.AddField(
            model_name='performances',
            name='id_performers',
            field=models.ManyToManyField(to='cardfile.Performers'),
        ),
        migrations.AddField(
            model_name='artworks',
            name='id_authors_of_text',
            field=models.ManyToManyField(blank=True, null=True, to='cardfile.AuthorsOfText'),
        ),
        migrations.AddField(
            model_name='artworks',
            name='id_composers',
            field=models.ManyToManyField(blank=True, null=True, to='cardfile.Composers'),
        ),
        migrations.AddField(
            model_name='artworks',
            name='id_genres',
            field=models.ManyToManyField(blank=True, null=True, to='cardfile.Genres'),
        ),
    ]
