# Generated by Django 4.0.1 on 2023-04-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardfile', '0002_alter_artworks_id_alter_authorsoftext_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artworks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardfile.artwork')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('performers', models.ManyToManyField(to='cardfile.Performance')),
            ],
        ),
        migrations.RemoveField(
            model_name='performances',
            name='id_artworks',
        ),
        migrations.RemoveField(
            model_name='performances',
            name='id_performers',
        ),
        migrations.RemoveField(
            model_name='records',
            name='id_performers',
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='AuthorOfText',
        ),
        migrations.RenameModel(
            old_name='Performers',
            new_name='Composer',
        ),
        migrations.RenameModel(
            old_name='Composers',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='AuthorsOfText',
            new_name='Performer',
        ),
        migrations.DeleteModel(
            name='Artworks',
        ),
        migrations.DeleteModel(
            name='Performances',
        ),
        migrations.DeleteModel(
            name='Records',
        ),
        migrations.AddField(
            model_name='performance',
            name='performers',
            field=models.ManyToManyField(to='cardfile.Performer'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='authors_of_text',
            field=models.ManyToManyField(blank=True, null=True, to='cardfile.AuthorOfText'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='composers',
            field=models.ManyToManyField(blank=True, null=True, to='cardfile.Composer'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='cardfile.Genre'),
        ),
    ]
